// Code generated by "stringer -type DataType parse.go"; DO NOT EDIT

package parse

import "fmt"

const _DataType_name = "COUNTERGAUGEDERIVEABSOLUTE"

var _DataType_index = [...]uint8{0, 7, 12, 18, 26}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return fmt.Sprintf("DataType(%d)", i)
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
