// Code generated by "stringer -type=PartType"; DO NOT EDIT

package parse

import "fmt"

const (
	_PartType_name_0 = "HostTimePluginPluginInstanceCPartTypeCPartTypeInstanceValuesIntervalTimeHighResIntervalHighRes"
	_PartType_name_1 = "MessageSeverity"
	_PartType_name_2 = "Signature"
	_PartType_name_3 = "Encryption"
)

var (
	_PartType_index_0 = [...]uint8{0, 4, 8, 14, 28, 37, 54, 60, 68, 79, 94}
	_PartType_index_1 = [...]uint8{0, 7, 15}
	_PartType_index_2 = [...]uint8{0, 9}
	_PartType_index_3 = [...]uint8{0, 10}
)

func (i PartType) String() string {
	switch {
	case 0 <= i && i <= 9:
		return _PartType_name_0[_PartType_index_0[i]:_PartType_index_0[i+1]]
	case 256 <= i && i <= 257:
		i -= 256
		return _PartType_name_1[_PartType_index_1[i]:_PartType_index_1[i+1]]
	case i == 512:
		return _PartType_name_2
	case i == 528:
		return _PartType_name_3
	default:
		return fmt.Sprintf("PartType(%d)", i)
	}
}
